### ISSUE TITLE
Path files

### ISSUE THREAD

**Issue by adiif1** [skullb0x/bluesaga#29]
`
C:\Users\User\git\bluesaga\CLIENT\release> java -jar gameData.jar
java.io.FileNotFoundException: libs\crashlogs\crashlog_20160809_005658.txt (System nie może odnaleźć określonej ścieżki)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.PrintStream.<init>(Unknown Source)
        at game.BlueSaga$1.uncaughtException(BlueSaga.java:314)
        at java.lang.ThreadGroup.uncaughtException(Unknown Source)
        at java.lang.ThreadGroup.uncaughtException(Unknown Source)
        at java.lang.Thread.dispatchUncaughtException(Unknown Source)
`

`Read language file: C:\Users\User\git\bluesaga\SERVER\release\test.jargame_text.json
java.io.FileNotFoundException: C:\Users\User\git\bluesaga\SERVER\release\test.jargame_text.json (Nie można odnaleźć określonego pliku)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at utils.LanguageSupport.loadLanguageFile(LanguageSupport.java:30)
        at network.Server.start(Server.java:111)
        at game.BPserver.main(BPserver.java:46)`

**Comment by Titousensei** [comment]
You need to run in dev mode: set DEV_MODE=true in ServerSettings.java
