### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by adiif1** [skullb0x/bluesaga#30]
`java.sql.SQLException: no such table: Streak
        at org.sqlite.DB.throwex(DB.java:288)
        at org.sqlite.NestedDB.prepare(NestedDB.java:115)
        at org.sqlite.DB.prepare(DB.java:114)
        at org.sqlite.Stmt.execute(Stmt.java:82)
        at game.Database.askDB(Database.java:45)
        at particlesystem.Streak.StreakContainer.CreateStreakFromDB(StreakContainer.java:24)
        at particlesystem.Streak.StreakContainer.<init>(StreakContainer.java:17)
        at screens.ScreenHandler.InitiateContainers(ScreenHandler.java:282)
        at screens.ScreenHandler.init(ScreenHandler.java:101)
        at game.BlueSaga.loading(BlueSaga.java:125)
        at game.BlueSaga.init(BlueSaga.java:106)
        at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
        at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:317)
        at game.BlueSaga.main(BlueSaga.java:369)`

**Comment by Titousensei** [comment]
Did you run the client in dev mode?
