### ISSUE TITLE
Editor does not work.

### ISSUE THREAD

**Issue by Titousensei** [skullb0x/bluesaga#8]
```
[13:56:53]WMD:~/src/bluesaga/EDITOR::master>./run
Sat Jul 30 13:56:54 PDT 2016 INFO:Slick Build #237
Sat Jul 30 13:56:54 PDT 2016 INFO:LWJGL Version: 2.9.2
Sat Jul 30 13:56:54 PDT 2016 INFO:OriginalDisplayMode: 1920 x 1080 x 24 @60Hz
Sat Jul 30 13:56:54 PDT 2016 INFO:TargetDisplayMode: 1024 x 640 x 0 @0Hz
Sat Jul 30 13:56:55 PDT 2016 INFO:Starting display 1024x640
Sat Jul 30 13:56:55 PDT 2016 INFO:Use Java PNG Loader = true
Sat Jul 30 13:56:55 PDT 2016 INFO:Controllers not available
CLIENT PATH: ../CLIENT/src/images/
java.sql.SQLException: no such table: area
    at org.sqlite.DB.throwex(DB.java:288)
    at org.sqlite.NativeDB.prepare(Native Method)
    at org.sqlite.DB.prepare(DB.java:114)
    at org.sqlite.Stmt.execute(Stmt.java:82)
    at game.Database.askDB(Database.java:162)
    at menus.MapMenu.load(MapMenu.java:42)
    at game.BP_EDITOR.init(BP_EDITOR.java:165)
    at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:317)
    at game.BP_EDITOR.main(BP_EDITOR.java:596)
Exception in thread "main" java.lang.NullPointerException
    at menus.MapMenu.load(MapMenu.java:45)
    at game.BP_EDITOR.init(BP_EDITOR.java:165)
    at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:317)
    at game.BP_EDITOR.main(BP_EDITOR.java:596)
```

I have a patch which changes all the "select from area" to "select from area_tile", but I'm not sure if it's the proper fix.

**Comment by Arkhist** [comment]
Editor works for me, I am using eclipse though

**Comment by Arkhist** [comment]
Seems like it looks for the map.db in "/CLIENT/src/images/" which is not correct.

The table 'area' should be present, so it is not the proper fix.

**Comment by Titousensei** [comment]
Hmm, that's strange, I loaded both mapDB.db files with sqlite3 directly, and none of them contain the table 'area'.

**Comment by Titousensei** [comment]
What's the schema of the table 'area'?

**Comment by skullb0x** [comment]
It is not used anymore i think. You can remove it. It was an older version which had separate areas that used that.

**Comment by Titousensei** [comment]
Closed by merge. Works for me now.
